Addr = "127.0.0.1:3306"
root_user = "root"
root_password = "123456"

[database]
  [database.auth_db]
    Username = "auth_db"
    Password = "nMoKrF2Rm3i2iQixYyhBgjDK"
  [database.file_reader]
    Username = "file_reader"
    Password = "qwYBjUq9f!s5m8cw1OVvIeaD"
  [database.file_writer]
    Username = "file_writer"
    Password = "OcRKZkfSUK2LyjUvDw1sM3GG"
